### Sign In
POST https://rematesvirtuales.dian.gov.co/remate-virtual/api/auth/signin
Content-Type: application/json

{
  "usernameOrEmail": "EnEtldJjmen8BQk8XlbS6Ua5f7W3MhQ5lMmOEnIWyxM=",
  "password": "JWG4oaaul1oX+fxYdUDO/r7HPcxjwMPnRDHfgf2oy5I="
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.global.set("Token", response.body.accessToken)
    });
%}

### Total of auctions
GET https://rematesvirtuales.dian.gov.co/remate-virtual/api/v1/revautos/list/count
Authorization: Bearer {{Token}}

### Get list of auction
GET https://rematesvirtuales.dian.gov.co/remate-virtual/api/v1/revautos/list/0/25
Authorization: Bearer {{Token}}

### Get details of auction
GET https://rematesvirtuales.dian.gov.co/remate-virtual/api/v1/remate/bienes/getAll/2033
Authorization: Bearer {{Token}}

### Get key of auction
GET https://rematesvirtuales.dian.gov.co/remate-virtual/api/v1/revautos/palabrasClave/2033
Authorization: Bearer {{Token}}

### Get official of auction
GET https://rematesvirtuales.dian.gov.co/remate-virtual/api/v1/remate/contactarencargado/buscarencagadobyauto/2033
Authorization: Bearer {{Token}}

### Get image
POST https://rematesvirtuales.dian.gov.co/remate-virtual/api/v1/common/getBlobStorageInvitadoPorNroRadicado
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "nroRadicado": 52631376187261,
  "usuarioSistema": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDIxNzU2MDcsInN1YiI6Ijk5OS0xIiwiYXVkIjpbIldvMGFLQWxCN3ZSUF8xNmZyUEkxeDlacGhCRWEiXSwiaXNzIjoiaHR0cHM6XC9cL211aXNjYS5kaWFuLmdvdi5jbyIsImp0aSI6IjUwNTE4NDVjLWEzNTktNDE5Yy1iM2NjLWU1NGYyZWYzN2FjOSIsImlhdCI6MTc0MjE3MjAwN30._n8Xf1UgXZuk6M5jiw67eAmcNU-THbnvBC85K8qVUdI"
}